name: Build latest (3DS)
on: [push]

concurrency:
  group: ${{ github.ref }}-3ds
  cancel-in-progress: true

jobs:
  build-3DS:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkitarm:latest
    steps:
      - uses: actions/checkout@v3
      - name: compile
        run: |
          make 3ds

      - uses: ./.github/actions/notify_failure
        if: ${{ steps.compile.outputs.status == 'failure' }}
        with:
          NOTIFY_MESSAGE: 'Failed to compile 3DS build'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'
          
      - uses: ./.github/actions/upload_build
        if: ${{ steps.compile.outputs.status == 'success' }}
        with:
          SOURCE_FILE: 'ClassiCube-3ds'
          DEST_NAME: 'latest/3ds/ClassiCube'