name: Build latest (3DS)
on: [push]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkitarm:latest
    steps:
      - uses: actions/checkout@v3
      - name: Compile
        run: |
          make 3ds

  notify-failure:
    runs-on: ubuntu-20.04
    needs: [build]
    if: ${{ always() && (needs.build.result == 'failure') }}
    steps:
      - name: Notify failure
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          username: Actions buildbot
          args: Failed to build latest commit for 3DS