name: Build latest (3DS)
on: [push]

concurrency:
  group: ${{ github.ref }}-3ds
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkitarm:latest
    steps:
      - uses: actions/checkout@v3
      - name: Compile
        run: |
          make 3ds

  notify-failure:
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ always() && (needs.build.result == 'failure') }}
    steps:
      - uses: actions/checkout@v3 # Necessary to access local action
      - uses: ./.github/actions/notify_failure
        with:
          NOTIFY_MESSAGE: 'Failed to compile 3DS build'
          WEBHOOK_URL: '${{ secrets.secrets.WEBHOOK_URL }}'