name: Build latest (Linux 64 bit)
on: [push]

concurrency:
  group: ${{ github.ref }}-linux64
  cancel-in-progress: true

jobs:
  build:
    if: github.ref_name == github.event.repository.default_branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Compile 64 bit Linux builds
        shell: bash
        id: compile
        run: |
          ALL_FLAGS="-O1 -s -fno-stack-protector -fno-math-errno -Qn"
          NIX64_FLAGS ="-no-pie -fno-pie -m64 -fvisibility=hidden -fcf-protection=none -rdynamic -DCC_BUILD_ICON"
          LATEST=$(git rev-parse --short "$GITHUB_SHA")
          
          gcc *.c $ALL_FLAGS $NIX64_FLAGS -DCC_COMMIT_SHA=\"$LATEST\" -o cc-nix64-gl1 -lX11 -lXi -lpthread -lGL -lm -ldl
          gcc *.c $ALL_FLAGS $NIX64_FLAGS -DCC_COMMIT_SHA=\"$LATEST\" -DCC_BUILD_GLMODERN -o cc-nix64-gl2 -lX11 -lXi -lpthread -lGL -lm -ldl

      - uses: ./.github/actions/notify_failure
        if: ${{ always() && steps.compile.outcome == 'failure' }}
        with:
          NOTIFY_MESSAGE: 'Failed to compile 64 bit Linux build'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'
          
      - uses: ./.github/actions/upload_build
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          SOURCE_FILE: 'cc-nix64-gl1'
          DEST_NAME: 'cc-nix64-gl1'
          
      - uses: ./.github/actions/upload_build
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          SOURCE_FILE: 'cc-nix64-gl2'
          DEST_NAME: 'cc-nix64-gl2'