name: Build latest (PSP)
on: [push]

concurrency:
  group: ${{ github.ref }}-psp
  cancel-in-progress: true

jobs:
  build-PSP:
    if: github.ref_name == github.event.repository.default_branch
    runs-on: ubuntu-latest
    container:
      image: pspdev/pspdev:latest
    steps:
      - uses: actions/checkout@v4
      - name: Compile PSP build
        id: compile
        run: |
          apk add curl curl-dev
          make psp
          

      - uses: ./.github/actions/notify_failure
        if: ${{ always() && steps.compile.outcome == 'failure' }}
        with:
          NOTIFY_MESSAGE: 'Failed to compile PSP build'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'
          
          
      - uses: ./.github/actions/upload_build
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          SOURCE_FILE: 'EBOOT.PBP'
          DEST_NAME: 'EBOOT.PBP'
          
      - uses: ./.github/actions/upload_build
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          SOURCE_FILE: 'ClassiCube-psp.elf'
          DEST_NAME: 'ClassiCube-psp.elf'
          
          
      - uses: ./.github/actions/notify_success
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          DESTINATION_URL: '${{ secrets.NOTIFY_URL }}'
          WORKFLOW_NAME: 'psp'