name: Build latest (Xbox)
on: [push]

concurrency:
  group: ${{ github.ref }}-xbox
  cancel-in-progress: true

jobs:
  build-Xbox:
    if: github.ref_name == github.event.repository.default_branch
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/xboxdev/nxdk:git-e955705a
    steps:
      - uses: actions/checkout@v3
      - name: Compile Xbox build
        id: compile
        run: |
          cd /usr/src/app
          make xbox

      - uses: ./.github/actions/notify_failure
        if: ${{ always() && steps.compile.outcome == 'failure' }}
        with:
          NOTIFY_MESSAGE: 'Failed to compile Xbox build'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'
          
      - uses: ./.github/actions/upload_build
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          SOURCE_FILE: 'ClassiCube.xbe'
          DEST_NAME: 'ClassiCube.xbe'