name: Build latest (PS1)
on: [push]

concurrency:
  group: ${{ github.ref }}-ps1
  cancel-in-progress: true

jobs:
  build-PS1:
    if: github.ref_name == github.event.repository.default_branch
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/classicube/minimal-psn00b:latest
    steps:
      - uses: actions/checkout@v4
      - name: Compile PS3 build
        id: compile
        run: |
          apt-get update
          apt-get install -y curl
          export PSNOOB=/usr/local/psnoob
          export PSL1GHT=/usr/local/ps3dev
          export PATH=$PATH:$PSNOOB/bin
          export PSN00BSDK_LIBS=$PSNOOB/lib/libpsn00b
          make ps1


      - uses: ./.github/actions/notify_failure
        if: ${{ always() && steps.compile.outcome == 'failure' }}
        with:
          NOTIFY_MESSAGE: 'Failed to compile PS1 build'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'


      - uses: ./.github/actions/upload_build
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          SOURCE_FILE: 'misc/ps1/build/template.elf'
          DEST_NAME: 'ClassiCube-PS1.elf'

      - uses: ./.github/actions/upload_build
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          SOURCE_FILE: 'misc/ps1/build/template.exe'
          DEST_NAME: 'ClassiCube-PS1.exe'
          
      - uses: ./.github/actions/upload_build
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          SOURCE_FILE: 'misc/ps1/build/template.bin'
          DEST_NAME: 'ClassiCube-PS1.bin'
          
      - uses: ./.github/actions/upload_build
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          SOURCE_FILE: 'misc/ps1/build/template.cue'
          DEST_NAME: 'ClassiCube-PS1.cue'
          
          
      - uses: ./.github/actions/notify_success
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          DESTINATION_URL: '${{ secrets.NOTIFY_URL }}'
          WORKFLOW_NAME: 'ps1'
