name: Build latest (Dreamcast)
# trigger via either push to selected branches or on manual run
on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-dreamcast
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kazade/dreamcast-sdk
    steps:
      - uses: actions/checkout@v4
      - name: Compile Dreamcast build
        id: compile
        run: |
          source /opt/toolchains/dc/kos/environ.sh
          export PATH=/opt/toolchains/dc/kos/utils/img4dc/build/cdi4dc/:$PATH
          make dreamcast
          

      - uses: ./.github/actions/notify_failure
        if: ${{ always() && steps.compile.outcome == 'failure' }}
        with:
          NOTIFY_MESSAGE: 'Failed to compile Dreamcast build'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'
          
          
      - uses: ./.github/actions/upload_build
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          SOURCE_FILE: 'ClassiCube-dc.cdi'
          DEST_NAME: 'ClassiCube-dc.cdi'
          
      - uses: ./.github/actions/upload_build
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          SOURCE_FILE: 'ClassiCube-dc.elf'
          DEST_NAME: 'ClassiCube-dc.elf'
          
          
      - uses: ./.github/actions/notify_success
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          DESTINATION_URL: '${{ secrets.NOTIFY_URL }}'
          WORKFLOW_NAME: 'dreamcast'