name: Build latest (Xbox 360)
on: [push]

concurrency:
  group: ${{ github.ref }}-xbox360
  cancel-in-progress: true

jobs:
  build-Xbox:
    if: github.ref_name == github.event.repository.default_branch
    runs-on: ubuntu-latest
    container:
      image: free60/libxenon
    steps:
      - uses: actions/checkout@v3
      - name: Compile 360 build
        id: compile
        run: |
          export DEVKITXENON=/usr/local/xenon
          export PATH=$PATH:$DEVKITXENON/bin:$DEVKITXENON/usr/bin
          make xbox360
          find .

      # otherwise notify_failure doesn't work
      - name: Install curl when necessary
        if: ${{ always() && steps.compile.outcome == 'failure' }}
        run: apt-get install -y curl

      - uses: ./.github/actions/notify_failure
        if: ${{ always() && steps.compile.outcome == 'failure' }}
        with:
          NOTIFY_MESSAGE: 'Failed to compile Xbox 360 build'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'