name: Build latest (Xbox 360)
on: [push]

concurrency:
  group: ${{ github.ref }}-xbox360
  cancel-in-progress: true

jobs:
  build-Xbox:
    if: github.ref_name == github.event.repository.default_branch
    runs-on: ubuntu-latest
    container:
      image: free60/libxenon
    steps:
      - uses: actions/checkout@v3
      - name: Compile 360 build
        id: compile
        run: |
          make 360
          find .