name: Build latest (Webclient)
on: [push]

concurrency:
  group: ${{ github.ref }}-web2
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python 3.x
        uses: actions/setup-python@v4
      - name: Compiles webclient
        id: compile
        run: |
          wget -q https://github.com/emscripten-core/emsdk/archive/1.38.48.tar.gz
          tar -xvf 1.38.48.tar.gz
          emsdk-1.38.48/emsdk update
          emsdk-1.38.48/emsdk install 1.38.48-fastcomp
          emsdk-1.38.48/emsdk activate 1.38.4-fastcomp
          pushd emsdk-1.38.48
          source ./emsdk_env.sh
          popd  
          cd src
          emcc *.c -O1 -o ClassiCube.js --js-library interop_web.js -s WASM=0 -s LEGACY_VM_SUPPORT=1 -s ALLOW_MEMORY_GROWTH=1 -s ABORTING_MALLOC=0 -s ENVIRONMENT=web
          sed -i 's#eventHandler.useCapture);#{ useCapture: eventHandler.useCapture, passive: false });#g' ClassiCube.js

      - uses: ./.github/actions/notify_failure
        if: ${{ always() && steps.compile.outcome == 'failure' }}
        with:
          NOTIFY_MESSAGE: 'Failed to compile Webclient'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'
          
      - uses: ./.github/actions/upload_build
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          SOURCE_FILE: 'src/ClassiCube.js'
          DEST_NAME: 'ClassiCube.js'