name: Build latest (RPI 64 bit)
on: [push]

concurrency:
  group: ${{ github.ref }}-rpi64
  cancel-in-progress: true

jobs:
  build-RPI64:
    if: github.ref_name == github.event.repository.default_branch
    runs-on: ubuntu-latest
    container:
      image: dockcross/linux-arm64-lts
    steps:
      - uses: actions/checkout@v3
      - name: Retrieve OpenGL and X11 dev files
        run: |
          mkdir src/rpi
          cd src/rpi
          wget https://github.com/ClassiCube/rpi-compiling-stuff/raw/main/rpi64.zip
          unzip rpi64.zip     
      - name: Compile RPI 64 bit build
        id: compile
        env: 
          COMMON_FLAGS: "-O1 -s -fno-stack-protector -fno-math-errno -Qn"
          RPI64_FLAGS: "-fvisibility=hidden -rdynamic -DCC_BUILD_ICON -DCC_BUILD_RPI -I rpi/include -L rpi/lib -Wl,--unresolved-symbols=ignore-in-shared-libs"
        run: |
          LATEST_FLAG=-DCC_COMMIT_SHA=\"$GITHUB_SHA\"
          
          cd src
          $CC *.c ${{ env.COMMON_FLAGS }} ${{ env.RPI64_FLAGS }} $LATEST_FLAG -o cc-rpi64 -lGLESv2 -lEGL -lX11 -lXi -lm -lpthread -ldl -lrt

      - uses: ./.github/actions/notify_failure
        if: ${{ always() && steps.compile.outcome == 'failure' }}
        with:
          NOTIFY_MESSAGE: 'Failed to compile RPI 64 bit build'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'
          
      - uses: ./.github/actions/upload_build
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          SOURCE_FILE: 'src/cc-rpi64'
          DEST_NAME: 'cc-rpi64'