name: Build latest (NDS)
on: [push]

concurrency:
  group: ${{ github.ref }}-nds
  cancel-in-progress: true

jobs:
  build-DS:
    if: github.ref_name == github.event.repository.default_branch
    runs-on: ubuntu-latest
    container:
      image: skylyrac/blocksds:dev-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compile NDS build
        id: compile
        run: |
          apt-get -y install curl
          export BLOCKSDS=/opt/blocksds/core
          export BLOCKSDSEXT=/opt/blocksds/external
          make ds


      - uses: ./.github/actions/notify_failure
        if: ${{ always() && steps.compile.outcome == 'failure' }}
        with:
          NOTIFY_MESSAGE: 'Failed to compile NDS build'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'
 
         
      - uses: ./.github/actions/upload_build
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          SOURCE_FILE: 'ClassiCube.nds'
          DEST_NAME: 'ClassiCube.nds'
          
      - uses: ./.github/actions/upload_build
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          SOURCE_FILE: 'build-nds/ClassiCube.elf'
          DEST_NAME: 'ClassiCube-nds.elf'
          
          
      - uses: ./.github/actions/notify_success
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          DESTINATION_URL: '${{ secrets.NOTIFY_URL }}'
          WORKFLOW_NAME: 'nds'
