name: Build latest (Saturn)
on: [push]

concurrency:
  group: ${{ github.ref }}-saturn
  cancel-in-progress: true

jobs:
  build:
    if: github.ref_name == github.event.repository.default_branch
    runs-on: ubuntu-latest
    container:
      image: ijacquez/yaul
    steps:
      - uses: actions/checkout@v4
      - name: Compile Saturn build
        id: compile
        run: |
          make saturn

      - uses: ./.github/actions/notify_failure
        if: ${{ always() && steps.compile.outcome == 'failure' }}
        with:
          NOTIFY_MESSAGE: 'Failed to compile Saturn build'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'
          
          
      - uses: ./.github/actions/upload_build
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          SOURCE_FILE: 'build-saturn/ClassiCube-saturn.elf'
          DEST_NAME: 'ClassiCube-saturn.elf'
          
      - uses: ./.github/actions/upload_build
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          SOURCE_FILE: 'ClassiCube-saturn.iso'
          DEST_NAME: 'ClassiCube-saturn.iso'