name: Build latest (macOS 32 bit)
on: [push]

concurrency:
  group: ${{ github.ref }}-mac32
  cancel-in-progress: true

jobs:
  build:
    if: github.ref_name == github.event.repository.default_branch
    runs-on: macOS-12
    steps:
      - uses: actions/checkout@v4
      - name: Compile 64 bit macOS builds
        shell: bash
        id: compile
        env: 
          COMMON_FLAGS: "-O1 -s -fno-stack-protector -fno-math-errno -Qn"
          MAC64_FLAGS:  "-fvisibility=hidden -rdynamic -DCC_BUILD_ICON -arch i386"
        run: |
          xcode-select --switch /Applications/Xcode_13.1.app
          LATEST_FLAG=-DCC_COMMIT_SHA=\"$(git rev-parse --short "$GITHUB_SHA")\"  
          
          cd src
          clang *.c interop_cocoa.m ${{ env.COMMON_FLAGS }} ${{ env.MAC64_FLAGS }} $LATEST_FLAG -o cc-mac32-gl1 -framework Cocoa -framework OpenGL -framework IOKit -lobjc
          clang *.c interop_cocoa.m ${{ env.COMMON_FLAGS }} ${{ env.MAC64_FLAGS }} $LATEST_FLAG -DCC_BUILD_GLMODERN -o cc-mac32-gl2 -framework Cocoa -framework OpenGL -framework IOKit -lobjc


      - uses: ./.github/actions/notify_failure
        if: ${{ always() && steps.compile.outcome == 'failure' }}
        with:
          NOTIFY_MESSAGE: 'Failed to compile 32 bit macOS build'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'
          
          
      - uses: ./.github/actions/upload_build
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          SOURCE_FILE: 'src/cc-mac32-gl1'
          DEST_NAME: 'ClassiCube-mac32'
          
      - uses: ./.github/actions/upload_build
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          SOURCE_FILE: 'src/cc-mac32-gl2'
          DEST_NAME: 'ClassiCube-mac32-ModernGL'