name: Build latest (Haiku)
on: [push]

concurrency:
  group: ${{ github.ref }}-haiku
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: haiku/cross-compiler:x86_64-r1beta4
    steps:
      - uses: actions/checkout@v3
      - name: Compile
        run: |
          cd src        
          x86_64-unknown-haiku-gcc *.c interop_BeOS.cpp -o ClassiCube-haiku -O1 -s -fno-stack-protector -fno-math-errno -Qn -lm -lGL -lnetwork -lstdc++ -lbe -lgame -ltracker

  notify-failure:
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ always() && (needs.build.result == 'failure') }}
    steps:
      - uses: actions/checkout@v3 # Necessary to access local action
      - uses: ./.github/actions/notify_failure
        with:
          NOTIFY_MESSAGE: 'Failed to compile Haiku build'
          WEBHOOK_URL: '${{ secrets.secrets.WEBHOOK_URL }}'