name: Build latest (PSP)
on: [push]

concurrency:
  group: ${{ github.ref }}-psp
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: pspdev/pspdev:latest
    steps:
      - uses: actions/checkout@v3
      - name: Compile
        run: |
          make psp

  notify-failure:
    needs: [build]
    if: ${{ always() && (needs.build.result == 'failure') }}
    steps:
      - uses: actions/checkout@v3 # Necessary to access local action
      - uses: ./.github/actions/notify_failure
        with:
          NOTIFY_MESSAGE: 'Failed to compile PSP build'
        secrets: inherit