name: Build release
on: [workflow_dispatch]

concurrency:
  group: ${{ github.ref }}-release
  cancel-in-progress: true

jobs:
  build:
    if: github.ref_name == github.event.repository.default_branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Download resources
      - name: Retrieve classicube texture pack
        run: |
          wget https://www.classicube.net/static/default.zip
      - name: Retrieve classicube audio pack
        run: |
          wget https://www.classicube.net/static/audio.zip
          
      # Download windows artifacts
      - name: Download 32 bit windows
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: build_windows.yml
          name: ClassiCube-Win32-Direct3D9.exe
      - name: Download 64 bit windows
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: build_windows.yml
          name: ClassiCube-Win64-Direct3D9.exe
          
      # Download Linux artifacts
      - name: Download 32 bit Linux
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: build_linux.yml
          name: ClassiCube-Linux32-OpenGL
      - name: Download 64 bit Linux
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: build_linux.yml
          name: ClassiCube-Linux64-OpenGL
          
      # Download macOS artifacts
      - name: Retrieve macOS binaries
        run: |
          wget https://cdn.classicube.net/client/latest/ClassiCube.64.osx -O cc-mac64
          wget https://cdn.classicube.net/client/latest/ClassiCube.osx -O cc-mac32
          
      - name: Generate builds
        id: compile
        shell: bash
        run: |
          mkdir ClassiCube
          mkdir ClassiCube/audio
          mkdir ClassiCube/texpacks
          cp audio.zip ClassiCube/audio/classicube.zip
          cp default.zip ClassiCube/texpacks/classicube.zip
          
          # ./ClassiCube
          make_unix_tar() {
            cp $2 ClassiCube/ClassiCube
            chmod +x ClassiCube/ClassiCube
            tar -zcvf $1 ClassiCube
            rm ClassiCube/ClassiCube
          }
           
          # ./ClassiCube
          make_windows_zip() {
            cp $2 ClassiCube/ClassiCube.exe
            zip $1 ClassiCube
            rm ClassiCube/ClassiCube.exe
          }
          
          # Generate Linux builds
          make_unix_tar cc-linux32.tar.gz cc-nix32-gl1
          make_unix_tar cc-linux64.tar.gz cc-nix64-gl1
          
          # Generate macOS builds
          make_unix_tar cc-mac32.tar.gz cc-mac32
          make_unix_tar cc-mac64.tar.gz cc-mac64
          
          # Generate Windows builds
          make_windows_zip cc-win32.zip cc-w32-d3d9.exe
          make_windows_zip cc-win64.zip cc-w64-d3d9.exe


      - uses: ./.github/actions/notify_failure
        if: ${{ always() && steps.compile.outcome == 'failure' }}
        with:
          NOTIFY_MESSAGE: 'Failed to produce release'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'
          
        
      # Generate Linux release files
      - uses: ./.github/actions/upload_build
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          SOURCE_FILE: 'cc-linux32.tar.gz'
          DEST_NAME: 'cc-linux32.tar.gz'
          
      - uses: ./.github/actions/upload_build
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          SOURCE_FILE: 'cc-linux64.tar.gz'
          DEST_NAME: 'cc-linux64.tar.gz'
          
          
      # Generate macOS release files
      - uses: ./.github/actions/upload_build
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          SOURCE_FILE: 'cc-mac32.tar.gz'
          DEST_NAME: 'cc-mac32.tar.gz'
          
      - uses: ./.github/actions/upload_build
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          SOURCE_FILE: 'cc-mac64.tar.gz'
          DEST_NAME: 'cc-mac64.tar.gz'
          
          
      # Generate Windows release files
      - uses: ./.github/actions/upload_build
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          SOURCE_FILE: 'cc-win32.zip'
          DEST_NAME: 'cc-win32.zip'
          
      - uses: ./.github/actions/upload_build
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          SOURCE_FILE: 'cc-win64.zip'
          DEST_NAME: 'cc-win64.zip'