name: Build latest (Wii/GameCube)
on: [push]

concurrency:
  group: ${{ github.ref }}-wiigc
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkitppc:latest
    steps:
      - uses: actions/checkout@v3
      - name: Compile
        run: |
          make wii
          make clean
          make gamecube

  notify-failure:
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ always() && (needs.build.result == 'failure') }}
    steps:
      - uses: actions/checkout@v3 # Necessary to access local action
      - uses: ./.github/actions/notify_failure
        with:
          NOTIFY_MESSAGE: 'Failed to compile Wii/GameCube build'